In [77]:
import numpy as np
import pandas as pd

In [78]:
df = pd.read_csv("/content/iris.data", header = None)

In [79]:
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [80]:
df.columns = ["Sepal length", "Sepal width", "Petal length", "Petal width", "species"]

In [81]:
df.head()

   Sepal length  Sepal width  Petal length  Petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [82]:
df = df[(df["species"]=="Iris-versicolor") | (df["species"]=="Iris-virginica")]

In [83]:
df.reset_index(drop=True, inplace=True)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal length  100 non-null    float64
 1   Sepal width   100 non-null    float64
 2   Petal length  100 non-null    float64
 3   Petal width   100 non-null    float64
 4   species       100 non-null    object
dtypes: float64(4), object(1)
memory usage: 4.0+ KB

In [85]:
test_index = np.random.randint(0, 99, 20)

In [86]:
test_df = []
for i in test_index:
  test_df.append(df.loc[i])

In [87]:
test_df = pd.DataFrame(test_df)

In [88]:
test_df.reset_index(drop=True, inplace=True)

In [89]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal length  20 non-null     float64
 1   Sepal width   20 non-null     float64
 2   Petal length  20 non-null     float64
 3   Petal width   20 non-null     float64
 4   species       20 non-null     object
dtypes: float64(4), object(1)
memory usage: 932.0+ bytes

Doing the same for training dataset

In [90]:
train_df = df.drop(index=test_index).reset_index(drop=True)

In [91]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal length  81 non-null     float64
 1   Sepal width   81 non-null     float64
 2   Petal length  81 non-null     float64
 3   Petal width   81 non-null     float64
 4   species       81 non-null     object
dtypes: float64(4), object(1)
memory usage: 3.3+ KB

In [92]:
train_df["species"].value_counts()

species
Iris-virginica     42
Iris-versicolor    39
Name: count, dtype: int64

In [93]:
test_df["species"].value_counts()

species
Iris-versicolor    11
Iris-virginica      9
Name: count, dtype: int64

In [94]:
X_train = train_df.drop("species", axis=1)
y_train = train_df["species"]
X_test = test_df.drop("species", axis=1)
y_test = test_df["species"]

In [95]:
y_train[y_train=="Iris-versicolor"] = 0
y_train[y_train=="Iris-virginica"] = 1
y_test[y_test=="Iris-versicolor"] = 0
y_test[y_test=="Iris-virginica"] = 1

<ipython-input-95-9a96438a4e28>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_train[y_train=="Iris-versicolor"] = 0
<ipython-input-95-9a96438a4e28>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_train[y_train=="Iris-virginica"] = 1
<ipython-input-95-9a96438a4e28>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test[y_test=="Iris-versicolor"] = 0
<ipython-input-95-9a96438a4e28>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test[y_test=="Iris-virginica"] = 1

In [96]:
X_train = np.array(X_train, dtype=np.float64)
y_train = np.array(y_train, dtype=np.float64)
X_test = np.array(X_test, dtype=np.float64)
y_test = np.array(y_test, dtype=np.float64)

In [97]:
def sigmoid(z):
 return 1/(1+np.exp(-z))

In [98]:
def calculate_cost(X, y, W, b):
  m,n = X.shape
  loss_sum = 0
  for i in range(m):
    z = 0
    for j in range(n):
      z += W[j] * X[i][j]
    z += b
    y_hat = sigmoid(z)
    loss = -(y[i] * np.log(y_hat)) - ((1-y[i]) * np.log(1-y_hat))
    loss_sum += loss
  cost = loss_sum/m
  return cost

In [99]:
def gradient(X, y, W, b):
  m,n = X.shape
  dj_dw = np.zeros(W.shape)
  dj_db = 0
  for i in range(m):
    z = 0
    for j in range(n):
      z += W[j] * X[i][j]
    z += b
    y_hat = sigmoid(z)
    dj_db += (y_hat - y[i])
    for j in range(n):
      dj_dw[j] += (y_hat - y[i]) * X[i][j]
  dj_db /= m
  dj_dw /= m
  return dj_db, dj_dw

In [100]:
def GD(X, y, W, b, l, iters):
  m,n = X.shape
  costs = []
  for i in range(iters):
    dj_db, dj_dw = gradient(X, y, W, b)
    W = W - l * dj_dw
    b = b - l * dj_db
    cost = calculate_cost(X, y, W, b)
    costs.append(cost)
    if (i%100==0):
      print(f"Iteration {i}: Cost = {cost}")
  return W, b, costs

In [101]:
W_in = np.zeros(X_train.shape[1])
b_in = 0
W, b, cost_history = GD(X_train, y_train, W_in, b_in, 0.1, 10000)

Iteration 0: Cost = 0.6886413376190326
Iteration 100: Cost = 0.45540276185143563
Iteration 200: Cost = 0.3522915771771817
Iteration 300: Cost = 0.29619416649108854
Iteration 400: Cost = 0.2612421635721289
Iteration 500: Cost = 0.2373729997949042
Iteration 600: Cost = 0.2199947158617215
Iteration 700: Cost = 0.2067386830761105
Iteration 800: Cost = 0.1962648186378414
Iteration 900: Cost = 0.18775911949356908
Iteration 1000: Cost = 0.18069868645857776
Iteration 1100: Cost = 0.17473214827310643
Iteration 1200: Cost = 0.16961450867559114
Iteration 1300: Cost = 0.16516959635639028
Iteration 1400: Cost = 0.1612673848890745
Iteration 1500: Cost = 0.15780973966907014
Iteration 1600: Cost = 0.15472115105684012
Iteration 1700: Cost = 0.15194252945111017
Iteration 1800: Cost = 0.1494269423447872
Iteration 1900: Cost = 0.14713661844707876
Iteration 2000: Cost = 0.14504079948595927
Iteration 2100: Cost = 0.1431141719080345
Iteration 2200: Cost = 0.14133570329277373
Iteration 2300: Cost = 0.1396877663511684
Iteration 2400: Cost = 0.13815547063714645
Iteration 2500: Cost = 0.13672614652507217
Iteration 2600: Cost = 0.13538894233054202
Iteration 2700: Cost = 0.1341345065552497
Iteration 2800: Cost = 0.13295473491231236
Iteration 2900: Cost = 0.13184256717380702
Iteration 3000: Cost = 0.13079182271293688
Iteration 3100: Cost = 0.12979706637282112
Iteration 3200: Cost = 0.1288534983054881
Iteration 3300: Cost = 0.1279568629071431
Iteration 3400: Cost = 0.12710337307961292
Iteration 3500: Cost = 0.12628964687765976
Iteration 3600: Cost = 0.12551265423127908
Iteration 3700: Cost = 0.124769671913568
Iteration 3800: Cost = 0.12405824529599137
Iteration 3900: Cost = 0.12337615572127486
Iteration 4000: Cost = 0.12272139254977409
Iteration 4100: Cost = 0.12209212911288425
Iteration 4200: Cost = 0.12148670194790108
Iteration 4300: Cost = 0.12090359280105706
Iteration 4400: Cost = 0.12034141297553053
Iteration 4500: Cost = 0.11979888967384224
Iteration 4600: Cost = 0.11927485404292498
Iteration 4700: Cost = 0.11876823067808424
Iteration 4800: Cost = 0.11827802838131027
Iteration 4900: Cost = 0.11780333200164367
Iteration 5000: Cost = 0.11734329521192946
Iteration 5100: Cost = 0.11689713409835858
Iteration 5200: Cost = 0.11646412145756696
Iteration 5300: Cost = 0.11604358171140924
Iteration 5400: Cost = 0.115634886362382
Iteration 5500: Cost = 0.11523744992350493
Iteration 5600: Cost = 0.11485072626559721
Iteration 5700: Cost = 0.11447420533263122
Iteration 5800: Cost = 0.11410741018241348
Iteration 5900: Cost = 0.11374989431545295
Iteration 6000: Cost = 0.11340123925965268
Iteration 6100: Cost = 0.11306105238257061
Iteration 6200: Cost = 0.11272896490651754
Iteration 6300: Cost = 0.11240463010479311
Iteration 6400: Cost = 0.11208772165998694
Iteration 6500: Cost = 0.11177793216753787
Iteration 6600: Cost = 0.11147497176971591
Iteration 6700: Cost = 0.1111785669069037
Iteration 6800: Cost = 0.1108884591745474
Iteration 6900: Cost = 0.11060440427544807
Iteration 7000: Cost = 0.11032617105821088
Iteration 7100: Cost = 0.11005354063366835
Iteration 7200: Cost = 0.10978630556196803
Iteration 7300: Cost = 0.10952426910380021
Iteration 7400: Cost = 0.10926724452991285
Iteration 7500: Cost = 0.10901505448367181
Iteration 7600: Cost = 0.10876753039195766
Iteration 7700: Cost = 0.10852451192015737
Iteration 7800: Cost = 0.10828584646744005
Iteration 7900: Cost = 0.10805138869886999
Iteration 8000: Cost = 0.10782100011125183
Iteration 8100: Cost = 0.10759454862989068
Iteration 8200: Cost = 0.1073719082337265
Iteration 8300: Cost = 0.10715295860652786
Iteration 8400: Cost = 0.1069375848120548
Iteration 8500: Cost = 0.10672567699128063
Iteration 8600: Cost = 0.10651713007994225
Iteration 8700: Cost = 0.10631184354483901
Iteration 8800: Cost = 0.10610972113743918
Iteration 8900: Cost = 0.10591067066348159
Iteration 9000: Cost = 0.10571460376736691
Iteration 9100: Cost = 0.10552143573024303
Iteration 9200: Cost = 0.10533108528077674
Iteration 9300: Cost = 0.10514347441768784
Iteration 9400: Cost = 0.10495852824320007
Iteration 9500: Cost = 0.10477617480663136
Iteration 9600: Cost = 0.10459634495740792
Iteration 9700: Cost = 0.10441897220684555
Iteration 9800: Cost = 0.10424399259809129
Iteration 9900: Cost = 0.10407134458366842

In [102]:
def predict(X, W, b):
  m, n = X.shape
  y_pred = np.zeros(m)
  for i in range(m):
    z = 0
    for j in range(n):
      z += W[j] * X[i][j]
    z += b
    y_hat = sigmoid(z)
    y_pred[i] = round(y_hat)
  return y_pred

In [103]:
p = predict(X_test, W, b)
print("Accuracy: %f"%(np.mean(p == y_test) * 100))

Accuracy: 100.000000